server:
  port: 8080
# 数据源配置
spring:
  #  spring.thymeleaf.prefix=classpath:/templates/ # 注意：加了斜杠
  #  spring.thymeleaf.suffix=.html
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource

    # Druid相关配置
    druid:
      # 表示启用插件监控结果的视图，默认匹配模式是druid
      stat-view-servlet:
        enabled: true

      # 默认的过滤器，stat表示启用统计过滤器
      filter: stat

      # 数据库驱动类名
      driver-class-name: com.mysql.cj.jdbc.Driver

      # 数据库基本信息
      url: jdbc:mysql://localhost/contact_manager?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 1234

      # 配置初始化大小、最小、最大
      initial-size: 1
      min-idle: 1
      max-active: 20

      # 获取连接等待超时时间
      max-wait: 60000

      # 间隔多久一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000

      # 一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000

      # 验证查询语句
      validation-query: SELECT 'x'

      # 空闲连接的检查方式
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      # 是否缓存预编译语句
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zyw.springboot_learning.entity

# PageHelper配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check


